//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thing.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class missing
    {
        public int Id { get; set; }

        [DisplayName ("Dog Name")]
        public string DogName { get; set; }

        [DisplayName("Dog Breed")]
        public string DogBreed { get; set; }

        [DisplayName("Last Known Location")]
        public string LastKnownLocation { get; set; }

        [DisplayName("Contact Number")]
        public string ContactNumber { get; set; }


        public Nullable<bool> Found { get; set; }
    }
}
